# prettier-ignore
name: Build and Deploy
on:
  push:
     branches:
        - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run-script build:prod
      - name: Archive Build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Echo
        run: ls; pwd;
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npx semantic-release@22
